/**
 * The hosted front end: repository name in, film out.
 *
 * All the work happens in modules shared with the CLI. `fetchHistory` gathers
 * the datasets, `buildPayload` compacts them, `buildHtml` inlines them into the
 * player. The page you see in the frame is byte-identical to the one the
 * download button hands you, because it is the same string.
 */

import { fetchHistory, parseRepo, checkRate, planBudget } from './src/github.js';
import { buildPayload, buildHtml } from './src/payload.js';

const $ = (id) => document.getElementById(id);
const TOKEN_KEY = 'sediment.token';

let templatePromise = null;
const playerTemplate = () => {
  if (!templatePromise) {
    templatePromise = fetch(new URL('./src/player.html', import.meta.url)).then((r) => {
      if (!r.ok) throw new Error('could not load the player template');
      return r.text();
    });
  }
  return templatePromise;
};

function status(text, bad = false) {
  const el = $('msg');
  el.textContent = text;
  el.className = bad ? 'bad' : '';
}
const progress = (pct) => {
  $('bar').style.width = `${Math.round(Math.max(0, Math.min(1, pct)) * 100)}%`;
};

/** Blob URLs back both the frame and the download, so they can never diverge. */
let objectUrls = [];
function freshUrl(text, type) {
  const url = URL.createObjectURL(new Blob([text], { type }));
  objectUrls.push(url);
  return url;
}

// Restore a token the visitor pasted earlier. Storage can throw in private
// windows, so every access is guarded.
try {
  const saved = localStorage.getItem(TOKEN_KEY);
  if (saved) $('token').value = saved;
} catch {
  /* storage unavailable */
}

/**
 * Put a payload on screen and behind the download buttons.
 *
 * The frame and the download are the same blob, so what gets saved is exactly
 * what is on screen.
 * @param {object} payload
 * @param {{scroll?: boolean}} [options]
 */
async function present(payload, options = {}) {
  const html = buildHtml(await playerTemplate(), payload);

  for (const u of objectUrls) URL.revokeObjectURL(u);
  objectUrls = [];
  const htmlUrl = freshUrl(html, 'text/html');
  const jsonUrl = freshUrl(JSON.stringify(payload), 'application/json');
  const slug = payload.title.replace(/[^\w.-]+/g, '-');

  $('frame').src = htmlUrl;
  $('dlHtml').href = htmlUrl;
  $('dlHtml').download = `${slug}-sediment.html`;
  $('dlJson').href = jsonUrl;
  $('dlJson').download = `${slug}-sediment.json`;
  $('stage').classList.add('on');
  if (options.scroll) $('stage').scrollIntoView({ behavior: 'smooth', block: 'start' });

  const m = payload.meta;
  $('summary').textContent =
    `${payload.title} · ${m.commits.toLocaleString()} commits · ` +
    `${m.contributors.toLocaleString()} contributors · ${m.spanDays.toLocaleString()} days`;
}

/**
 * Render something real before anyone types anything.
 *
 * The demo payload ships with the site and was generated by the CLI, so it
 * costs no API requests, cannot be rate-limited, and carries exact line counts
 * rather than the byte sizes a live build has to settle for.
 */
async function showDemo() {
  try {
    const res = await fetch(new URL('./demo.json', import.meta.url));
    if (!res.ok) return;
    await present(await res.json());
    $('demoNote').hidden = false;
    status('Type any public repository above to build its history.');
  } catch {
    /* no demo shipped, so the form is all there is */
  }
}

async function build(input, token) {
  const parsed = parseRepo(input);
  if (!parsed) {
    status('That does not look like a repository. Try owner/name.', true);
    return;
  }

  $('go').disabled = true;
  $('demoNote').hidden = true;
  progress(0.02);
  status('Checking your request budget…');

  try {
    // Without a token GitHub allows 60 requests an hour per address, and a
    // mid-sized repository wants more than that. Ask first, then fetch only
    // what fits, rather than failing halfway through.
    const rate = await checkRate(token);
    const plan = planBudget(rate.remaining);
    if (rate.remaining < 6) {
      const mins = rate.reset
        ? Math.max(1, Math.ceil((rate.reset * 1000 - Date.now()) / 60000))
        : 0;
      status(
        `GitHub's rate limit is spent${mins ? `. It resets in about ${mins} min` : ''}. ` +
          'Add a token to lift it to 5,000 an hour.',
        true
      );
      $('go').disabled = false;
      return;
    }
    $('rate').textContent = `${rate.remaining} of ${rate.limit} API requests left this hour`;
    status(`Reading ${parsed.owner}/${parsed.repo}…`);

    const { datasets, rateRemaining, truncated } = await fetchHistory({
      ...parsed,
      token,
      maxCommits: plan.maxCommits,
      anchors: plan.anchors,
      onProgress: (m, pct) => {
        status(m);
        if (typeof pct === 'number') progress(0.05 + pct * 0.85);
      },
    });

    progress(0.94);
    status('Building the film…');
    await present(buildPayload(datasets), { scroll: true });

    progress(1);
    status(
      truncated
        ? `Done. The most recent ${m.commits.toLocaleString()} commits, which is what the ` +
            `remaining request budget covered.${token ? '' : ' A token fetches the rest.'}`
        : `Done. ${m.commits.toLocaleString()} commits.`
    );
    if (rateRemaining !== null && rateRemaining !== undefined) {
      $('rate').textContent = `${rateRemaining} API requests left this hour`;
    }
    location.hash = `${parsed.owner}/${parsed.repo}`;
  } catch (err) {
    progress(0);
    status(err.message || String(err), true);
  } finally {
    $('go').disabled = false;
  }
}

$('form').addEventListener('submit', (e) => {
  e.preventDefault();
  const token = $('token').value.trim();
  try {
    if (token) localStorage.setItem(TOKEN_KEY, token);
    else localStorage.removeItem(TOKEN_KEY);
  } catch {
    /* storage unavailable */
  }
  build($('repo').value, token);
});

for (const chip of document.querySelectorAll('[data-example]')) {
  chip.addEventListener('click', () => {
    $('repo').value = chip.dataset.example;
    $('form').requestSubmit();
  });
}

$('copyLink').addEventListener('click', async () => {
  try {
    await navigator.clipboard.writeText(location.href);
    status('Link copied.');
  } catch {
    status('Copy the address bar to share this.', true);
  }
});

// A repo in the hash makes every result shareable, and lets a README link
// straight to a specific repository's film.
function fromHash() {
  const hash = decodeURIComponent(location.hash.replace(/^#/, '')).trim();
  if (!hash) {
    showDemo();
    return;
  }
  $('repo').value = hash;
  let token = '';
  try {
    token = localStorage.getItem(TOKEN_KEY) || '';
  } catch {
    /* storage unavailable */
  }
  build(hash, token);
}
fromHash();
